feat: Implement cache bookend to use store-cli
screwdriver-cd/cache-bookend pull request #1
Opened 2018-10-15 23:29 UTC by pranavrc

https://github.com/screwdriver-cd/screwdriver/issues/1284

2018-10-15 23:54 UTC, d2lam commented on CONTRIBUTING.md
> +# Contributing
Can just point to our doc like this: https://github.com/screwdriver-cd/store-cli/blob/master/CONTRIBUTING.md

2018-10-16 00:09 UTC, tkyi commented on LICENSE
> +Copyright 2016 Yahoo Inc.
2018

2018-10-16 00:11 UTC, minzcmu requested changes

2018-10-16 00:11 UTC, minz1027 commented on index.js
> +                    const eventMap = this.jobCache.map(item =>
this.jobsCache can be undefined, then `this.jobCache.map` will fail

2018-10-16 00:11 UTC, minz1027 commented on index.js
> +                    const eventMap = this.jobCache.map(item =>
same thing here

2018-10-16 00:13 UTC, tkyi approved these changes
Small comment, otherwise LGTM

2018-10-16 00:27 UTC, Filbird commented on index.js
> +                    this.jobCache = hoek.reach(response.body, 'cache.event');
Would it be better conventionally for `jobCache` to be a local variable?

2018-10-17 17:42 UTC, d2lam commented on index.js
> +        return Promise.resolve('');
maybe can do `echo "skipping cache bookend because SD_USE_CACHE is false` for transparency

2018-10-17 22:33 UTC, d2lam commented on index.js
> +                    if (jobCache) {
let's also check the length of this `>0`. It could be `[]` as long as there is a `cache`, not necessary `cache.event`. It would result in `&&`

2018-10-17 23:32 UTC, d2lam approved these changes

2018-10-17 23:33 UTC, merged